version: '3.8'

volumes:
  postgres_data:
  static:

services:

  db:
    image: postgres:12.4
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  web:
    image: s10dev/yamdb:latest
    depends_on:
      - db
    volumes:
      - static:/app/static/
    ports:
      - "8000:8000"

  nginx:
    image: s10dev/nginx:latest
    ports: 
      - '80:80'
    depends_on:
      - db
      - web
    volumes:
      - static:/static/