# Generated by Django 3.0.5 on 2021-04-07 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0011_title_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
    ]
